"use strict";
exports.__esModule = true;
var mobileCollection_1 = require("./mobileCollection");
var mobile_1 = require("./mobile");
var a50 = new mobile_1.Mobile("A50", "Samsung", "premiun", "grey", 400);
var a72 = new mobile_1.Mobile("A72", "Samsung", "5G", "black", 500);
var a100 = new mobile_1.Mobile("A100", "Samsung", "premiun+", "white", 1000);
var a500 = new mobile_1.Mobile("A500", "LG", "alpha", "blue", 1500);
var myCollection = new mobileCollection_1.mobileCollection([a100, a50, a500, a72]);
myCollection.getMobiles();
myCollection.getTotalPrice();
myCollection.setTotalPrice(5000);
myCollection.setMobiles([a500, a100]);
myCollection.printCollection();
